### PR TITLE
Fix bundling exports from 4.0 in 3.8 compat mode

### PR DESCRIPTION
**Pull request by dapetcu21**
When exporting from Spine 4.0 in Spine 3.8 compatibility mode, the version string is something like `3.8-from-4.0.47`, which trips up the `Integer.parseInt(scene.spineVersionParts[1])` calls because they try to parse `8-from-4` as a number.

I didn't test this PR btw. I just did it with Github's web UI.

### CODE REVIEW

**Comment by britzl** [comment]
> I didn't test this PR btw. I just did it with Github's web UI.

Let us know when you've tested this yourself. Or if you can provide a spine export with a version string as in your example so that someone else can test the fix.

**Comment by dapetcu21** [comment]
Sorry for not testing. I would, but I don't think I know how to test this myself, since it seems that the plugin needs to be compiled into a .jar (?) and I don't know how exactly to do that.

Here's a simple Spine 4.0 export in 3.8 compatibility mode:

[leaves.zip](https://github.com/defold/extension-spine/files/7762468/leaves.zip)

**Comment by JCash** [comment]
To build the plugins, you can use the [ build_plugins.sh](https://github.com/defold/extension-spine/blob/main/utils/build_plugins.sh) script.
It requires a bob.jar, and it will send a build request to the could build server.
After that, you should have a .jar file (and 3 shared libraries)

**Comment by dapetcu21** [comment]
Thanks! I completely missed that script! I tested with the above leaf.json before and after building the plugins and can confirm that that regex change fixes the issue.

I built with:
`DEFOLDSDK=6bfeea3b13d7b8920483ea2cba9c181a8650b84d BOB=defold-stable-1.2.190/bob.jar utils/build_plugins.sh`

**Review by britzl — APPROVED** [review]
Looks good! I've tested and can confirm that it is working with the example spine model provided and with existing spine models

**Pull request merged**
