### PR TITLE
Added spine gui script api

### PR DESCRIPTION
**Pull request by britzl**
Fix https://github.com/defold/extension-spine/issues/89

### CODE REVIEW

**Review by JCash — APPROVED** [review]

**Comment by AGulev** [comment]
hmm, why it's not merged ?

**Comment by AGulev** [comment]
`set_spine_attachment` missed

**Comment by britzl** [comment]
> `set_spine_attachment` missed

Added!

**Comment by AGulev** [comment]
@britzl should we merge it?

**Comment by britzl** [comment]
Yes! Forgot about it!

**Pull request merged**
